SEED = 67
NUM_CITIES = 10
DISTANCE_MIN = 1
DISTANCE_MAX = 30

POPULATION_SIZE = 1000
NUM_GENERATIONS = 50
NUM_PARENTS_MATING = 50

PARENT_SELECTION = "tournament"
TOURNAMENT_K = 3
CROSSOVER_TYPE = "single_point"
MUTATION_TYPE = "inversion"
MUTATION_PERCENT_GENES = 3